import './compile.js';
import './node.js';
import './base.js';
import './accounts.js';
import './deploy/test.js';
import './ens-encoded-dns/test.js';
import './calls.js';
import './console.js';
import './merge.js';
